const presets = {
    'default': {
        nome: "ComMarília Padrão",
        json: `{\n  "tema": {\n    "theme_dark": "#0F172A",\n    "theme_light": "#F8FAFC",\n    "theme_brand": "#FF5A26",\n    "font_url": "",\n    "font_main": "'Montserrat', sans-serif",\n    "font_display": "'Bebas Neue', sans-serif",\n    "custom_css": ""\n  },\n  "cards": []\n}`
    },
    'anos2000': {
        nome: "Retrô Anos 2000",
        json: `{\n  "tema": {\n    "theme_dark": "#121220",\n    "theme_light": "#FAFAFA",\n    "theme_brand": "#FF007F",\n    "highlight_1_name": "--theme-cyan",\n    "highlight_1_color": "#00F0FF",\n    "font_url": "https://fonts.googleapis.com/css2?family=Righteous&family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap",\n    "font_main": "'Space Mono', monospace",\n    "font_display": "'Righteous', sans-serif",\n    "custom_css": ".storie-wrapper { box-shadow: 12px 12px 0px rgba(0, 0, 0, 1); border: 4px solid #000; border-radius: 16px; } body { background-image: linear-gradient(rgba(0, 240, 255, 0.1) 1px, transparent 1px), linear-gradient(90deg, rgba(0, 240, 255, 0.1) 1px, transparent 1px); background-size: 40px 40px; } .storie-title { text-shadow: 6px 6px 0px #000, -2px -2px 0 #000, 2px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000; } .tag-pill { border: 4px solid #000; box-shadow: 6px 6px 0px #000; border-radius: 0; color: #000; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(18, 18, 32, 0.85); backdrop-filter: blur(5px); padding: 30px; border: 4px solid #000; box-shadow: 10px 10px 0px #000; }"\n  },\n  "cards": []\n}`
    },
    'historico': {
        nome: "Histórico / Sépia Clássico",
        json: `{\n  "tema": {\n    "theme_dark": "#231A16",\n    "theme_light": "#F4E8D1",\n    "theme_brand": "#FF5A26",\n    "highlight_1_name": "--theme-yellow",\n    "highlight_1_color": "#D4AF37",\n    "highlight_2_name": "--theme-orange",\n    "highlight_2_color": "#A05C3A",\n    "highlight_3_name": "--theme-red",\n    "highlight_3_color": "#8C3B24",\n    "font_url": "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Montserrat:wght@400;500;600;700;800;900&display=swap",\n    "font_main": "'Montserrat', sans-serif",\n    "font_display": "'Bebas Neue', sans-serif",\n    "custom_css": ".gradient-bottom { background: linear-gradient(to top, rgba(35, 26, 22, 0.98) 0%, rgba(35, 26, 22, 0.8) 35%, transparent 70%); } .control-btn { background: rgba(35, 26, 22, 0.8); border: 3px solid var(--theme-light); box-shadow: 0 4px 10px rgba(0,0,0,0.5); color: var(--theme-light); } .zoom-panel { background: rgba(35, 26, 22, 0.9); border: 2px solid rgba(244, 232, 209, 0.2); } .tag-pill { box-shadow: 0 5px 15px rgba(0,0,0,0.4); border-radius: 60px; font-weight: 800; color: var(--theme-dark); } .storie-title { text-shadow: 2px 4px 10px rgba(0,0,0,0.6); } .storie-text { font-weight: 500; } .storie-text strong { font-weight: 800; } .text-wrapper-left { border-left: 8px solid; padding-left: 30px; } .text-wrapper-center { border-bottom: 8px solid; padding-bottom: 30px; } .text-wrapper-right { border-right: 8px solid; padding-right: 30px; }"\n  },\n  "cards": []\n}`
    },
    'financas': {
        nome: "Finanças / Investimentos",
        json: `{\n  "tema": {\n    "theme_dark": "#0A1C15",\n    "theme_light": "#F8F9FA",\n    "theme_brand": "#FF5A26",\n    "highlight_1_name": "--theme-green",\n    "highlight_1_color": "#2ECC71",\n    "highlight_2_name": "--theme-gold",\n    "highlight_2_color": "#F4B41A",\n    "highlight_3_name": "--theme-blue",\n    "highlight_3_color": "#3498DB",\n    "font_url": "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&family=Playfair+Display:ital,wght@0,700;0,800;0,900;1,700&display=swap",\n    "font_main": "'Montserrat', sans-serif",\n    "font_display": "'Playfair Display', serif",\n    "custom_css": ".gradient-bottom { background: linear-gradient(to top, var(--theme-dark) 0%, rgba(10, 28, 21, 0.9) 25%, rgba(10, 28, 21, 0) 75%); } .control-btn { border: 4px solid white; box-shadow: 0 4px 10px rgba(0,0,0,0.5); } .tag-pill { display: inline-block; color: #111; font-family: var(--font-display); font-size: 35px; font-weight: 800; padding: 10px 40px; border-radius: 100px; text-transform: uppercase; letter-spacing: 2px; box-shadow: 0 4px 10px rgba(0,0,0,0.3); } .storie-title { text-transform: uppercase; text-shadow: 2px 4px 15px rgba(0,0,0,0.8); } .storie-text { text-shadow: 1px 2px 8px rgba(0,0,0,0.9); } .text-wrapper-left { border-left: 10px solid; padding-left: 40px; } .text-wrapper-center { border-top: 10px solid; padding-top: 40px; } .text-wrapper-right { border-right: 10px solid; padding-right: 40px; }"\n  },\n  "cards": []\n}`
    },
    'tech_cyber': {
        nome: "Tecnologia / Cyberpunk",
        json: `{\n  "tema": {\n    "theme_dark": "#050510",\n    "theme_light": "#E0E7FF",\n    "theme_brand": "#00FFCC",\n    "highlight_1_name": "--theme-magenta",\n    "highlight_1_color": "#FF00FF",\n    "font_url": "https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500&family=Orbitron:wght@500;700;900&display=swap",\n    "font_main": "'Fira Code', monospace",\n    "font_display": "'Orbitron', sans-serif",\n    "custom_css": ".storie-wrapper { border: 2px solid var(--theme-brand); box-shadow: 0 0 20px rgba(0, 255, 204, 0.3); } .storie-title { text-transform: uppercase; text-shadow: 0 0 10px var(--theme-brand); letter-spacing: 2px; } .tag-pill { border: 1px solid var(--theme-brand); color: var(--theme-brand); background: rgba(0, 255, 204, 0.1); border-radius: 4px; box-shadow: 0 0 10px rgba(0,255,204,0.5); font-weight: 700; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(5, 5, 16, 0.9); border-left: 4px solid var(--theme-magenta); padding: 25px; }"\n  },\n  "cards": []\n}`
    },
    'moda_editorial': {
        nome: "Moda / Editorial",
        json: `{\n  "tema": {\n    "theme_dark": "#111111",\n    "theme_light": "#FFFFFF",\n    "theme_brand": "#D4AF37",\n    "font_url": "https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,wght@0,400;0,700;1,400&family=Jost:wght@300;400;500&display=swap",\n    "font_main": "'Jost', sans-serif",\n    "font_display": "'Bodoni Moda', serif",\n    "custom_css": ".storie-wrapper { border-radius: 0; } .storie-title { font-weight: 400; letter-spacing: 1px; } .storie-text { font-weight: 300; letter-spacing: 0.5px; line-height: 1.6; } .tag-pill { background: transparent; border: 1px solid var(--theme-light); color: var(--theme-light); border-radius: 0; text-transform: uppercase; letter-spacing: 4px; font-family: var(--font-main); font-size: 12px; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(17, 17, 17, 0.85); backdrop-filter: blur(10px); padding: 40px; border: 1px solid rgba(255,255,255,0.2); }"\n  },\n  "cards": []\n}`
    },
    'infantil_ludico': {
        nome: "Infantil / Kids",
        json: `{\n  "tema": {\n    "theme_dark": "#2D3436",\n    "theme_light": "#FFFFFF",\n    "theme_brand": "#FF4757",\n    "highlight_1_name": "--theme-blue",\n    "highlight_1_color": "#1E90FF",\n    "highlight_2_name": "--theme-yellow",\n    "highlight_2_color": "#FFA502",\n    "font_url": "https://fonts.googleapis.com/css2?family=Fredoka+One&family=Nunito:wght@400;700;900&display=swap",\n    "font_main": "'Nunito', sans-serif",\n    "font_display": "'Fredoka One', cursive",\n    "custom_css": ".storie-wrapper { border-radius: 40px; border: 8px solid var(--theme-light); box-shadow: 0 15px 0px rgba(0,0,0,0.1); } .storie-title { text-shadow: 3px 3px 0px rgba(0,0,0,0.2); } .tag-pill { border-radius: 50px; font-family: var(--font-display); font-size: 18px; padding: 12px 25px; box-shadow: 0 6px 0px rgba(0,0,0,0.2); border: 3px solid var(--theme-light); } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(45, 52, 54, 0.8); border-radius: 30px; padding: 30px; border: 4px solid rgba(255,255,255,0.3); }"\n  },\n  "cards": []\n}`
    },
    'gastro_gourmet': {
        nome: "Gastronomia / Restaurante",
        json: `{\n  "tema": {\n    "theme_dark": "#2C1E16",\n    "theme_light": "#FDF5E6",\n    "theme_brand": "#E63946",\n    "highlight_1_name": "--theme-olive",\n    "highlight_1_color": "#606C38",\n    "font_url": "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,500;0,700;1,500&family=Lato:wght@300;400;700&display=swap",\n    "font_main": "'Lato', sans-serif",\n    "font_display": "'Cormorant Garamond', serif",\n    "custom_css": ".gradient-bottom { background: linear-gradient(to top, rgba(44, 30, 22, 0.95) 0%, rgba(44, 30, 22, 0.7) 40%, transparent 80%); } .storie-title { font-style: italic; } .tag-pill { background: var(--theme-brand); color: var(--theme-light); border-radius: 2px; font-family: var(--font-main); text-transform: uppercase; letter-spacing: 2px; font-weight: 700; padding: 8px 20px; } .text-wrapper-center { border-top: 2px solid var(--theme-brand); border-bottom: 2px solid var(--theme-brand); padding: 30px 20px; text-align: center; }"\n  },\n  "cards": []\n}`
    },
    'esportes_hardcore': {
        nome: "Esportes / Fitness",
        json: `{\n  "tema": {\n    "theme_dark": "#0B0B0C",\n    "theme_light": "#FFFFFF",\n    "theme_brand": "#EFFF00",\n    "font_url": "https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,400;0,700;1,700&family=Teko:wght@500;700&display=swap",\n    "font_main": "'Barlow Condensed', sans-serif",\n    "font_display": "'Teko', sans-serif",\n    "custom_css": ".storie-wrapper { text-transform: uppercase; } .storie-title { font-size: 110px; line-height: 0.85; margin-bottom: 10px; text-shadow: 4px 4px 0px var(--theme-brand); } .storie-text { font-size: 24px; font-weight: 700; font-style: italic; } .tag-pill { transform: skewX(-10deg); border-radius: 0; background: var(--theme-light); color: var(--theme-dark); font-family: var(--font-display); font-size: 28px; padding: 5px 20px; box-shadow: 4px 4px 0px var(--theme-brand); } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(11, 11, 12, 0.9); transform: skewX(-5deg); padding: 30px; border-left: 8px solid var(--theme-brand); } .text-wrapper-base > * { transform: skewX(5deg); }"\n  },\n  "cards": []\n}`
    },
    'minimalista_clean': {
        nome: "Minimalista / Clean",
        json: `{\n  "tema": {\n    "theme_dark": "#18181B",\n    "theme_light": "#FAFAFA",\n    "theme_brand": "#3F3F46",\n    "font_url": "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;800&display=swap",\n    "font_main": "'Inter', sans-serif",\n    "font_display": "'Inter', sans-serif",\n    "custom_css": ".storie-wrapper { border-radius: 24px; } .storie-title { font-weight: 800; letter-spacing: -1px; } .storie-text { font-weight: 400; color: rgba(250, 250, 250, 0.9); } .tag-pill { background: #FFFFFF; color: #000000; border-radius: 100px; font-weight: 600; font-size: 14px; padding: 8px 20px; box-shadow: 0 4px 14px rgba(0,0,0,0.1); } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(24, 24, 27, 0.6); backdrop-filter: blur(20px); border-radius: 20px; padding: 40px; border: 1px solid rgba(255,255,255,0.1); }"\n  },\n  "cards": []\n}`
    },
    'saude_bemestar': {
        nome: "Saúde / Bem-Estar",
        json: `{\n  "tema": {\n    "theme_dark": "#1C3D5A",\n    "theme_light": "#F0F8FF",\n    "theme_brand": "#48C9B0",\n    "highlight_1_name": "--theme-blue",\n    "highlight_1_color": "#5DADE2",\n    "font_url": "https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;800&family=Plus+Jakarta+Sans:wght@400;500;700&display=swap",\n    "font_main": "'Plus Jakarta Sans', sans-serif",\n    "font_display": "'Outfit', sans-serif",\n    "custom_css": ".storie-wrapper { border-radius: 30px; } .gradient-bottom { background: linear-gradient(to top, rgba(28, 61, 90, 0.9) 0%, rgba(28, 61, 90, 0.6) 50%, transparent 100%); } .tag-pill { background: rgba(72, 201, 176, 0.2); color: var(--theme-brand); border: 2px solid var(--theme-brand); border-radius: 50px; font-weight: 700; padding: 8px 24px; backdrop-filter: blur(4px); } .text-wrapper-base, [class^='text-wrapper'] { background: #FFFFFF; color: var(--theme-dark); border-radius: 24px; padding: 35px; box-shadow: 0 10px 30px rgba(0,0,0,0.1); } .storie-title { color: var(--theme-dark); text-shadow: none; } .storie-text { color: #4A5568; text-shadow: none; }"\n  },\n  "cards": []\n}`
    },
    'eco_natureza': {
        nome: "Eco / Natureza",
        json: `{\n  "tema": {\n    "theme_dark": "#1B2A1E",\n    "theme_light": "#F4F1EA",\n    "theme_brand": "#4A7C59",\n    "highlight_1_name": "--theme-earth",\n    "highlight_1_color": "#8B5A2B",\n    "font_url": "https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@500;700&family=Karla:wght@400;700&display=swap",\n    "font_main": "'Karla', sans-serif",\n    "font_display": "'Zilla Slab', serif",\n    "custom_css": ".storie-wrapper { border-radius: 12px; } .gradient-bottom { background: linear-gradient(to top, rgba(27, 42, 30, 0.95) 0%, rgba(27, 42, 30, 0.7) 40%, transparent 100%); } .tag-pill { background: var(--theme-brand); color: var(--theme-light); border-radius: 8px; font-family: var(--font-main); font-weight: 700; padding: 6px 18px; text-transform: uppercase; letter-spacing: 1px; } .text-wrapper-left { border-left: 6px solid var(--theme-brand); padding-left: 25px; }"\n  },\n  "cards": []\n}`
    },
    'educacao_academico': {
        nome: "Educação / Acadêmico",
        json: `{\n  "tema": {\n    "theme_dark": "#0D1B2A",\n    "theme_light": "#E0E1DD",\n    "theme_brand": "#1D3557",\n    "highlight_1_name": "--theme-red",\n    "highlight_1_color": "#E63946",\n    "font_url": "https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,500;0,700;1,500&family=Work+Sans:wght@400;500;600&display=swap",\n    "font_main": "'Work Sans', sans-serif",\n    "font_display": "'Lora', serif",\n    "custom_css": ".tag-pill { background: var(--theme-light); color: var(--theme-dark); font-family: var(--font-main); font-weight: 600; text-transform: uppercase; border-radius: 4px; padding: 8px 16px; letter-spacing: 1px; border-bottom: 3px solid var(--theme-brand); } .storie-title { line-height: 1.2; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(13, 27, 42, 0.9); border-top: 6px solid var(--theme-brand); padding: 35px; border-radius: 8px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }"\n  },\n  "cards": []\n}`
    },
    'gamer_neon': {
        nome: "Gamer / E-Sports",
        json: `{\n  "tema": {\n    "theme_dark": "#0D0D0D",\n    "theme_light": "#F2F2F2",\n    "theme_brand": "#7000FF",\n    "highlight_1_name": "--theme-cyan",\n    "highlight_1_color": "#00F0FF",\n    "font_url": "https://fonts.googleapis.com/css2?family=Chakra+Petch:ital,wght@0,500;0,700;1,700&family=Rajdhani:wght@500;600;700&display=swap",\n    "font_main": "'Rajdhani', sans-serif",\n    "font_display": "'Chakra Petch', sans-serif",\n    "custom_css": ".storie-wrapper { border-radius: 0; } .storie-title { text-transform: uppercase; text-shadow: 2px 2px 0px var(--theme-brand), -2px -2px 0px var(--theme-cyan); } .tag-pill { background: var(--theme-dark); color: var(--theme-light); border: 2px solid var(--theme-brand); border-radius: 0; font-family: var(--font-display); font-size: 20px; font-weight: 700; text-transform: uppercase; padding: 8px 24px; box-shadow: inset 0 0 10px rgba(112, 0, 255, 0.5); } .text-wrapper-base, [class^='text-wrapper'] { background: linear-gradient(135deg, rgba(13,13,13,0.95) 0%, rgba(30,30,30,0.95) 100%); border-right: 4px solid var(--theme-cyan); border-bottom: 4px solid var(--theme-brand); padding: 30px; clip-path: polygon(0 0, 100% 0, 100% 90%, 95% 100%, 0 100%); }"\n  },\n  "cards": []\n}`
    },
    'noticias_breaking': {
        nome: "Notícias / Breaking News",
        json: `{\n  "tema": {\n    "theme_dark": "#1A1A2E",\n    "theme_light": "#FFFFFF",\n    "theme_brand": "#E63946",\n    "highlight_1_name": "--theme-yellow",\n    "highlight_1_color": "#FFD60A",\n    "font_url": "https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;700&family=Source+Sans+3:wght@400;600;700&display=swap",\n    "font_main": "'Source Sans 3', sans-serif",\n    "font_display": "'Oswald', sans-serif",\n    "custom_css": ".storie-wrapper { border-radius: 0; border: 3px solid var(--theme-brand); } .storie-title { text-transform: uppercase; font-weight: 700; letter-spacing: 2px; text-shadow: 3px 3px 0 rgba(0,0,0,0.8); } .tag-pill { background: var(--theme-brand); color: white; border-radius: 0; font-family: var(--font-display); font-size: 22px; font-weight: 700; text-transform: uppercase; padding: 10px 28px; letter-spacing: 3px; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(26, 26, 46, 0.95); border-left: 6px solid var(--theme-brand); padding: 30px; border-radius: 0; } .gradient-bottom { background: linear-gradient(to top, rgba(26, 26, 46, 1) 0%, rgba(26, 26, 46, 0.9) 30%, transparent 70%); }"\n  },\n  "cards": []\n}`
    },
    'pets_vet': {
        nome: "Pets / Veterinário",
        json: `{\n  "tema": {\n    "theme_dark": "#2D3436",\n    "theme_light": "#FEFEFE",\n    "theme_brand": "#00B894",\n    "highlight_1_name": "--theme-pink",\n    "highlight_1_color": "#FD79A8",\n    "highlight_2_name": "--theme-yellow",\n    "highlight_2_color": "#FDCB6E",\n    "font_url": "https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;600;700&family=Baloo+2:wght@500;700;800&display=swap",\n    "font_main": "'Quicksand', sans-serif",\n    "font_display": "'Baloo 2', cursive",\n    "custom_css": ".storie-wrapper { border-radius: 32px; border: 4px solid rgba(255,255,255,0.2); } .storie-title { text-shadow: 2px 2px 0 rgba(0,0,0,0.2); } .tag-pill { border-radius: 50px; font-family: var(--font-display); padding: 12px 28px; box-shadow: 0 4px 0 rgba(0,0,0,0.15); border: 3px solid white; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(45, 52, 54, 0.75); backdrop-filter: blur(8px); border-radius: 24px; padding: 30px; border: 2px solid rgba(255,255,255,0.15); } .gradient-bottom { background: linear-gradient(to top, rgba(45, 52, 54, 0.95) 0%, rgba(45, 52, 54, 0.6) 40%, transparent 80%); }"\n  },\n  "cards": []\n}`
    },
    'imobiliario': {
        nome: "Imobiliário / Real Estate",
        json: `{\n  "tema": {\n    "theme_dark": "#1B1B2F",\n    "theme_light": "#F5F0EB",\n    "theme_brand": "#C9A96E",\n    "highlight_1_name": "--theme-navy",\n    "highlight_1_color": "#1B1B2F",\n    "font_url": "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;0,800;1,400&family=Raleway:wght@300;400;500;600&display=swap",\n    "font_main": "'Raleway', sans-serif",\n    "font_display": "'Playfair Display', serif",\n    "custom_css": ".storie-wrapper { border-radius: 4px; } .storie-title { font-weight: 400; letter-spacing: 2px; } .storie-text { font-weight: 300; letter-spacing: 0.3px; } .tag-pill { background: transparent; border: 2px solid var(--theme-brand); color: var(--theme-brand); border-radius: 0; text-transform: uppercase; letter-spacing: 5px; font-weight: 500; padding: 10px 30px; font-family: var(--font-main); font-size: 16px; } .text-wrapper-base, [class^='text-wrapper'] { background: rgba(27, 27, 47, 0.85); backdrop-filter: blur(15px); padding: 40px; border-top: 1px solid var(--theme-brand); border-bottom: 1px solid var(--theme-brand); border-radius: 0; } .gradient-bottom { background: linear-gradient(to top, rgba(27, 27, 47, 0.98) 0%, rgba(27, 27, 47, 0.7) 40%, transparent 80%); }"\n  },\n  "cards": []\n}`
    },
    'musica_festival': {
        nome: "Música / Festival",
        json: `{\n  "tema": {\n    "theme_dark": "#0D0221",\n    "theme_light": "#FFFFFF",\n    "theme_brand": "#FF6B6B",\n    "highlight_1_name": "--theme-purple",\n    "highlight_1_color": "#A855F7",\n    "highlight_2_name": "--theme-cyan",\n    "highlight_2_color": "#06B6D4",\n    "font_url": "https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Poppins:wght@400;600;800&display=swap",\n    "font_main": "'Poppins', sans-serif",\n    "font_display": "'Permanent Marker', cursive",\n    "custom_css": ".storie-wrapper { border-radius: 16px; border: 2px solid rgba(168, 85, 247, 0.4); box-shadow: 0 0 30px rgba(168, 85, 247, 0.15); } .storie-title { text-shadow: 0 0 20px rgba(255, 107, 107, 0.6), 0 0 40px rgba(168, 85, 247, 0.3); font-weight: 400; } .tag-pill { background: linear-gradient(135deg, var(--theme-brand), var(--theme-purple)); color: white; border-radius: 50px; font-family: var(--font-main); font-weight: 800; padding: 10px 28px; box-shadow: 0 0 15px rgba(255, 107, 107, 0.4); text-transform: uppercase; letter-spacing: 2px; } .text-wrapper-base, [class^='text-wrapper'] { background: linear-gradient(135deg, rgba(13, 2, 33, 0.9), rgba(30, 10, 60, 0.9)); backdrop-filter: blur(10px); border: 1px solid rgba(168, 85, 247, 0.3); border-radius: 20px; padding: 30px; } .gradient-bottom { background: linear-gradient(to top, rgba(13, 2, 33, 1) 0%, rgba(13, 2, 33, 0.8) 35%, transparent 75%); }"\n  },\n  "cards": []\n}`
    }
};